"""change announce column url to content

Revision ID: 7246a4b97f54
Revises: 0000e79a0e32
Create Date: 2018-02-26 11:47:44.911005

"""
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

# revision identifiers, used by Alembic.
from future import standard_library
standard_library.install_aliases()
from builtins import *
revision = '7246a4b97f54'
down_revision = '0000e79a0e32'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE announce RENAME COLUMN url TO content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE announce RENAME COLUMN content TO url')
    # ### end Alembic commands ###
